name: "home_credit_risk"
version: "1.0.0"
config-version: 2

profile: "home_credit_risk"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  home_credit_risk:
    description: >
      This project transforms raw Kaggle Home Credit data into a 
      risk assessment suite using an L1/L2/L3 architecture in Snowflake.

    staging:
      +schema: L2_PROCESSING # Exact name for Snowflake
      +materialized: view
      description: "Raw data transformations and basic cleaning. Materialized as views for flexibility."

    intermediate:
      +schema: L2_PROCESSING # Exact name for Snowflake
      +materialized: view
      description: "Intermediate transformations and aggregations. Materialized as views for flexibility."

    marts:
      +schema: L3_CONSUMPTION # Exact name for Snowflake
      +materialized: table
      description: "Final feature tables for modeling and analysis. Materialized as tables for performance."
